services:

  ur-gazebo:
    image: husarion/ur5e:melodic
    container_name: panther_gazebo
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      roslaunch ur5e_bringup ur5e_gazebo.launch
        use_rviz:=true

  webui-ros-joystick:
    image: husarion/webui-ros-joystick:noetic
    container_name: webui-ros-joystick
    environment:
      - ROS_MASTER_URI=http://panther_gazebo:11311
    ports:
      - 8000:8000
    command: roslaunch webui-ros-joystick panther_webui.launch --wait