services:

  ros_master:
    image: ros:noetic-ros-core
    container_name: ros_master
    network_mode: host
    restart: always
    environment:
      - ROS_IP=10.15.20.2
    command: roscore

  panther_ros:
    image: husarion/panther:noetic
    container_name: panther_ros
    network_mode: host
    restart: always
    tty: true
    environment:
      - ROS_IP=10.15.20.2
      - ROS_MASTER_URI=http://10.15.20.2:11311
      - PANTHER_HAS_CONFIG
      - PANTHER_IMU_LOCALIZATION_X
      - PANTHER_IMU_LOCALIZATION_Y
      - PANTHER_IMU_LOCALIZATION_Z
      - PANTHER_IMU_ORIENTATION_R
      - PANTHER_IMU_ORIENTATION_P
      - PANTHER_IMU_ORIENTATION_Y
      - PANTHER_ROBOT_VERSION
    devices:
      - /dev/bus/usb
      - /dev/gpiomem
      - /dev/spidev0.0
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - /tmp/panther_config.yaml:/tmp/panther_config.yaml
    command: roslaunch panther_bringup bringup.launch --wait

  webui-ros-joystick:
    image: husarion/webui-ros-joystick:noetic
    container_name: webui-ros-joystick
    network_mode: host
    restart: always
    environment:
      - ROS_IP=10.15.20.2
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: roslaunch webui-ros-joystick panther_webui.launch e_stop:=true --wait
