services:
  
  panther_gazebo:
    image: husarion/panther-gazebo:noetic-1.0.52-20230918-stable
    container_name: panther_gazebo
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./panther.rviz:/ros_ws/src/panther_description/rviz/panther.rviz
      - ./panther.urdf.xacro:/ros_ws/src/panther_description/urdf/panther.urdf.xacro
    command: roslaunch panther_gazebo panther_simulation.launch

  webui-ros-joystick:
    image: husarion/webui-ros-joystick:noetic-0.0.1-20230510-stable
    container_name: webui-ros-joystick
    environment:
      - ROS_MASTER_URI=http://panther_gazebo:11311
    ports:
      - 8000:8000
    command: >
      roslaunch --wait webui-ros-joystick panther_webui.launch 
        e_stop:=false