services:
  panther_gazebo:
    image: husarion/panther:noetic-simulation
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./panther.rviz:/ros_ws/src/panther_description/rviz/panther.rviz
      - ./panther.urdf.xacro:/ros_ws/src/panther_description/urdf/panther.urdf.xacro
      - ./panther_ouster.launch:/ros_ws/src/panther_gazebo/launch/panther_ouster.launch
    command: roslaunch panther_gazebo panther_ouster.launch