services:
  
  bridge:
    image: husarion/ros:galactic-ros1-bridge
    restart: always
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.2
      - ROS_MASTER_URI=http://10.15.20.2:11311
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    command: ros2 run ros1_bridge dynamic_bridge