services:

  rviz:
    image: husarion/rviz2:humble-11.2.8-20231122
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./panther.rviz:/root/.rviz/default.rviz
    environment: 
      - DISPLAY=${DISPLAY:?You need to define display env}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
