x-common-config: &common-config
  network_mode: host
  ipc: host
  restart: always
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # Default FastDDS do not work
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
services:
  panther_ros:
    image: husarion/panther-gazebo:humble-2.0.1-20240425
    container_name: panther_ros
    <<: *common-config
    devices:
      - /dev/bus/usb
      - /dev/gpiochip0
      - /dev/spidev0.0
      - /dev/spidev0.1
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - /sys/bus/iio/devices:/sys/bus/iio/devices
      - /run/husarion/panther_config.env:/run/husarion/panther_config.env
      - /run/husarion/panther_config.yaml:/run/husarion/panther_config.yaml
    # Realtime hardware (https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html#determinism)
    ulimits:
      rtprio:
        soft: 99
        hard: 99
      memlock:
        soft: 102400
        hard: 102400
    command: >
      ros2 launch panther_bringup bringup.launch.py namespace:=panther

  gamepad_controller:
    image: husarion/joy2twist:humble-1.0.0-20240109
    container_name: gamepad_controller
    <<: *common-config
    devices:
      - /dev/input/js0
    stop_signal: SIGINT
    command: >
      bash -c "ros2 launch joy2twist gamepad_controller.launch.py joy2twist_params_file:=$(ros2 pkg prefix joy2twist)/share/joy2twist/config/joy2twist_panther.yaml namespace:=panther"

