x-common-config:
  &common-config
  network_mode: host
  restart: always
  ipc: host
  tty: true
  environment:
    - ROS_IP=10.15.20.2
    - ROS_MASTER_URI=http://10.15.20.2:11311

services:
  ros_master:
    image: ros:noetic-ros-core
    container_name: ros_master
    <<: *common-config
    command: roscore

  panther_ros:
    image: husarion/panther:noetic-nightly
    container_name: panther_ros
    <<: *common-config
    devices:
      - /dev/bus/usb
      - /dev/gpiochip0
      - /dev/spidev0.0
      - /dev/spidev0.1
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - /sys/bus/:/sys/bus/
      - /run/husarion/panther_config.env:/run/husarion/panther_config.env
      - /run/husarion/panther_config.yaml:/run/husarion/panther_config.yaml
    command: >
      roslaunch --wait
      panther_bringup bringup.launch
      exit_on_wrong_hw:=false

  webui-ros-joystick:
    image: husarion/webui-ros-joystick:noetic-0.0.1-20230324-stable
    container_name: webui-ros-joystick
    <<: *common-config
    command: >
      roslaunch --wait
      webui-ros-joystick panther_webui.launch
      e_stop:=true

  gamepad_controller:
    image: husarion/joy2twist:noetic-1.0.0-20230324-stable
    container_name: gamepad_controller
    <<: *common-config
    devices:
      - /dev/input/js0
    command: >
      roslaunch --wait
      joy2twist gamepad_controller.launch
      joy2twist_params_file:=$$(find joy2twist)/config/joy2twist_panther.yaml
