x-common-config:
  &common-config
  network_mode: host
  ipc: host
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # TODO: Fix Default FastDDS

x-cpu-config:
  &cpu-config
  env_file: .env.cpu

x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:
  panther:
    image: husarion/panther-gazebo:humble-ros2-update
    # build:
    #   context: ..
    #   dockerfile: Dockerfile.simulation
    <<:
      - *common-config
      - *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch panther_gazebo simulation.launch.py
