x-common-config: &common-config
  network_mode: host
  ipc: host
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # Default FastDDS do not work
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
x-cpu-config: &cpu-config
  env_file: .env.cpu
x-gpu-config: &gpu-config
  runtime: nvidia
  env_file: .env.gpu
services:
  panther_gazebo:
    image: husarion/panther-gazebo:humble-2.0.1-20240430-stable
    container_name: panther_gazebo
    <<:
      - *common-config
      - *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch panther_gazebo simulation.launch.py

