x-common-config:
  &common-config
  network_mode: host
  restart: always
  ipc: host
  tty: true
  environment:
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

services:
  panther_ros:
    # image: husarion/panther:humble-nightly
    build: 
      context: ..
      dockerfile: Dockerfile.hardware
    container_name: panther_ros
    <<: *common-config
    devices:
      - /dev/bus/usb
      - /dev/gpiochip0
      - /dev/spidev0.0
      - /dev/spidev0.1
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - /sys/bus/iio/devices:/sys/bus/iio/devices
      - /run/husarion/panther_config.env:/run/husarion/panther_config.env
      - /run/husarion/panther_config.yaml:/run/husarion/panther_config.yaml
    command: >
      ros2 launch panther_bringup bringup.launch

  gamepad_controller:
    image: husarion/joy2twist:humble-1.0.0-20231205
    container_name: gamepad_controller
    <<: *common-config
    devices:
      - /dev/input/js0
    command: >
      bash -c
      "ros2 launch 
      joy2twist gamepad_controller.launch.py
      joy2twist_params_file:=$(ros2 pkg prefix joy2twist)/share/joy2twist/config/joy2twist_panther.yaml"
