services:

  panther_gazebo:
    image: husarion/panther-gazebo:humble-nightly
    container_name: panther_gazebo
    network_mode: host
    ipc: host
    runtime: nvidia
    tty: true
    environment:
      - DISPLAY=${DISPLAY:?You need to define display env}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch panther_gazebo simulation.launch.py
