services:

  panther_gazebo:
    image: husarion/panther-gazebo:noetic-1.0.21-20230717
    container_name: panther_gazebo
    runtime: nvidia
    tty: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: roslaunch panther_gazebo panther_simulation.launch

  webui-ros-joystick:
    image: husarion/webui-ros-joystick:noetic-0.0.1-20230510-stable
    container_name: webui-ros-joystick
    environment:
      - ROS_MASTER_URI=http://panther_gazebo:11311
    ports:
      - 8000:8000
    command: >
      roslaunch --wait webui-ros-joystick panther_webui.launch 
        e_stop:=false