---
name: Release repository

on:
    workflow_dispatch:
        inputs:
            target_branch:
                description: Target branch for the release.
                required: true
            version:
                description: New version (used for tag).
                required: true
            image_timestamp:
                description: Timestamp of the image to be used in the compose files.
                required: true
            release_name:
                description: Name of the release to be created. Version in the first place is recommended (e.g. `2.0.0-alpha`).
                required: true
            automatic_mode:
                type: boolean
                default: false
                description: Automatically merge PR and create release.
            prerelease:
                type: boolean
                default: false
                description: Mark the release as a prerelease.

jobs:
    release:
        name: Release repository
        runs-on: ubuntu-22.04
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            RELEASE_BRANCH: release-${{ github.event.inputs.version }}
            DOCKER_IMAGE: husarion/panther-gazebo:humble-${{ github.event.inputs.version }}-${{ github.event.inputs.image_timestamp }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.target_branch }}

            - name: Update docker image version
              uses: mikefarah/yq@v4.43.1
              with:
                  cmd: |
                      yq -i '.services.panther_ros.image = "${{ env.DOCKER_IMAGE }}" | (... | select(tag == "!!merge")) tag = ""' demo/compose.minimal-setup.yaml
                      yq -i '.services.panther_gazebo.image = "${{ env.DOCKER_IMAGE }}" | (... | select(tag == "!!merge")) tag = ""' demo/compose.simulation.yaml

            - name: Commit changes to release branch
              uses: EndBug/add-and-commit@v9
              with:
                  message: Update docker image version
                  author_name: action-bot
                  author_email: action-bot@action-bot.com
                  new_branch: ${{ env.RELEASE_BRANCH }}

            - name: Create pull request
              run: |
                  gh pr create \
                  --base ${{ github.event.inputs.target_branch }} \
                  --head $RELEASE_BRANCH \
                  --title "Release ${{ github.event.inputs.version }}" \
                  --body "This PR incorporates package(s) version and changelog update."

            - name: Merge pull request
              if: ${{ github.event.inputs.automatic_mode == true }}
              run: |
                  gh pr merge $RELEASE_BRANCH \
                  --delete-branch

            - name: Create tag
              if: ${{ github.event.inputs.automatic_mode == true }}
              run: |
                  git checkout ${{ github.event.inputs.target_branch }}
                  git tag ${{ github.event.inputs.version }}
                  git push origin ${{ github.event.inputs.version }}

            - name: Create prerelease
              if: ${{ github.event.inputs.automatic_mode == true && github.event.inputs.prerelease == true}}
              run: |
                  gh release create ${{ github.event.inputs.version }} \
                  --title ${{ github.event.inputs.release_name }} \
                  --notes-from-tag \
                  --prerelease

            - name: Create release
              if: ${{ github.event.inputs.automatic_mode == true && github.event.inputs.prerelease == false}}
              run: |
                  gh release create ${{ github.event.inputs.version }} \
                  --title ${{ github.event.inputs.release_name }} \
                  --notes-from-tag
